import Head from 'next/head' 
import Link from 'next/link'
import { useRouter } from 'next/router'
import { MouseEvent, useRef } from 'react'
import { postData } from '../../utils/utils'

export default function Home() {
  const userNameRef = useRef<HTMLInputElement>(null);
  const userEmailRef = useRef<HTMLInputElement>(null)
  const router = useRouter()
  const handleSignUp = async (e: MouseEvent<HTMLElement>) => {
    e.preventDefault()
    const data = 
      {
        username:userNameRef.current?.value,
        email:userEmailRef.current?.value
      }
    
    const res = await postData({url:'/api/users',data});
      if(res.status === 200) {
        router.push('/users')
      }
      
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <form>
        <div>
          <label htmlFor="username">username</label>
          <input type="text" id='username' ref={userNameRef} />

        </div>
        <div>
          <label htmlFor="email">email</label>
          <input type="email" id='email' ref={userEmailRef} />

        </div>
        <button onClick={handleSignUp}>sign up</button>
      </form>
      <Link href='/users' >
        go to users
      </Link>
    </>
  )
}
